# Generated by Django 5.1.7 on 2025-04-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='date',
        ),
    ]
