# Generated by Django 5.1.7 on 2025-04-03 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_rename_created_date_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.account'),
        ),
    ]
