# Generated by Django 5.1.7 on 2025-04-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_comment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
