# Generated by Django 5.1.7 on 2025-04-03 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_comment_first_name_comment_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='last_name',
        ),
    ]
