# Generated by Django 5.1.7 on 2025-04-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_remove_comment_first_name_remove_comment_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='pin',
            new_name='account_pin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
        migrations.AlterField(
            model_name='comment',
            name='currency',
            field=models.CharField(choices=[('GB', 'British Pounds'), ('Dollar', 'US Dollars'), ('Euro', 'European Euros')], max_length=100),
        ),
    ]
