# Generated by Django 5.1.7 on 2025-04-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
