# Generated by Django 5.1.7 on 2025-04-04 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_account_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
