# Generated by Django 5.1.7 on 2025-04-04 23:08

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdef1234567890', length=10, max_length=15, prefix='TR-', unique=True),
        ),
    ]
