# Generated by Django 5.1.7 on 2025-04-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_remove_transaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=750.0, max_digits=10),
        ),
    ]
