# Generated by Django 5.1.7 on 2025-04-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('GB', 'British Pounds'), ('Dollar', 'US Dollars'), ('Euro', 'European Euros')], default='GB', max_length=100),
        ),
    ]
