# Generated by Django 5.1.7 on 2025-04-06 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_transaction_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
    ]
