# Generated by Django 5.1.7 on 2025-04-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_remove_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('request', 'Request'), ('request_acc', 'Request Accepted'), ('request_rej', 'Request Rejected'), ('request_proc', 'Request Pending'), ('received', 'Received'), ('none', 'None')], default='none', max_length=100),
        ),
    ]
