# Generated by Django 5.1.7 on 2025-04-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('in-active', 'In-active')], default='active', max_length=100),
        ),
    ]
